spring:
  application:
    name: query-by-example
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: diallodev
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
    database: postgresql

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.testcontainers: INFO
